name: Build and deploy ExclusiveInsightsScheduler

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: ExclusiveInsightsScheduler
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ./published
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  SOLUTION_PATH: ExclusiveInsightsFuncApp/ExclusiveInsights.sln
  PROJECT_PATH: ExclusiveInsightsAPI/ExclusiveInsightsFuncApp/ExclusiveInsightsFuncApp.csproj

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.SOLUTION_PATH }}"

      - name: Publish Function App
        run: |
          dotnet publish "${{ env.PROJECT_PATH }}" \
            -c "${{ env.CONFIGURATION }}" \
            -o "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6255B9D15E2E461A8E409EBEE3B3AE65 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6D148C0A2A0D471FBABB09DCF444D129 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_70982A5D4B2344758A9E6D307BC5D740 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
